name: auth
description: Auth service.
version: 1.0.0
# homepage: https://www.mikenedviga.ru

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  conduit: 3.1.2
  jaguar_jwt: ^3.0.0
  conduit_common: 3.1.1
  conduit_codable: 3.1.1
  conduit_config: 3.1.1
  conduit_isolate_exec: 3.1.1
  conduit_open_api: 3.1.1
  conduit_password_hash: 3.1.1
  conduit_runtime: 3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
